### PR TITLE
migrate to nuxt 2.0

### PR DESCRIPTION
**Pull request by Ataww**
Following the discussion here https://github.com/nuxt-community/typescript-template/issues/54

- updated nuxt to 2.0.0
- updated Typescript to Typescript 3
- converted the nuxt config file and the typescript module to ES6 syntax
- Include a fix from https://github.com/nuxt-community/typescript-template/pull/47

### CODE REVIEW

**Comment by Ataww** [comment]
Following the discussion here https://github.com/nuxt-community/typescript-template/issues/54

- updated nuxt to 2.0.0
- updated Typescript to Typescript 3
- converted the nuxt config file and the typescript module to ES6 syntax

**Comment by P4sca1** [comment]
Guess we should tarket `"nuxt": "`2.0.0"` instead of `"nuxt": "2.0.0"` in `package.json` to include future versions of `nuxt` (like `nuxt 2.1.0).

**Comment by benmccallum** [comment]
Is this valid to be copied? Looking at setting up a new project and trying to use typescript and this looks like my best bet at the moment?

**Comment by Ataww** [comment]
I'm currently working on a project using this template so you should be able to use my fork with `vue init`

I will have a look at create-nuxt-app this evening.

**Comment by benmccallum** [comment]
I'm thinking of giving this a go: https://github.com/wagerfield/nuxt-typescript

Looks like a lot of thinking went into it 4 months ago, just hope it works out-of-the-box now that 2.0 has landed. https://cmty.app/nuxt/nuxt.js/issues/c6950

**Comment by hmsk** [comment]
By merging #57, now using Nuxt 2.3.4. Thanks for your waiting patiently ✨ 

will follow about separately:
> converted the nuxt config file and the typescript module to ES6 syntax

**Pull request closed without merging**
