### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by chepelevdi**
Fix problems with webpack

### CODE REVIEW

**Comment by mboudreau** [comment]
I've applied this change to my new nuxt project and it now works out of the box :)

**Comment by 9renpoto** [comment]
@chepelevdi Hi! Please rebase from HEAD. and please update dependencies :-)

**Comment by DrMabuse23** [comment]
Hi, why is this doesnt merge ?

**Comment by monzou** [comment]
ping ?

**Comment by hmsk** [comment]
The problem is solved in the latest of this repo ✨ 
Thanks for sending the PR!

**Pull request closed without merging**
